Make crate compatible with no_std
DavJCosby/sled pull request #86
Opened 2024-11-12 19:58 UTC by claudiomattera

This pull request makes the crate usable in `no_std` environments (`alloc` is still required).

Trivial changes:

*   I replaced all `std::collections::HashSet` and `std::collections::HashMap` with `alloc::collections::BTreeSet` and `alloc::collections::BTreeMap`.
    They should be nearly equivalent, unless there was an actual reason for using `HashMap` instead of `BTreeMap` that I missed.

*   I put the constructor for `Config` that takes a path and reads it from a file behind a feature `std`.
    On a `no_std` environment the client should load the configuration on their own, and pass it as a string.

*   I replaced all `std::time::Duration` with `core::time::Duration`.

Non-trivial changes:

*   `std::time::Instant` is not available in `core`, because without the operating system there is no general way to get the current time.
    I defined a trait in `time::Instant`, so clients can choose an appropriate representation for their platform.

    Then `Driver` takes a generic argument `INSTANT: Instant`.
    A predefined alias `StdDriver` is available for `std` platforms, using `std::time::Instant`, gated behind a feature.

*   `std::thread::sleep()` is also not available in `core`, and `spin_sleep` requires `std.`
    I defined a trait in `time::Sleeper`,  clients can choose an appropriate implementation for their platform.

    Then `Scheduler` takes two generic arguments `INSTANT: Instant` and `SLEEPER: Sleeper`.
    A predefined alias `StdScheduler` is available for `std` platforms, using `std::time::Instant` and `std::thread:sleep`, and another one `SpinScheduler`, using `std::time::Instant` and `spin_sleep::sleep`, both gated behind features.

*   I added an `AsyncSleeper` that has an `async` interface (embassy is getting popular in embedded Rust).

    `Scheduler` is the only place that handles sleeping, and it is not so big, so I simply duplicated the logic into `AsyncScheduler`.
    There might be a more clever approach using [`maybe-async`](https://docs.rs/maybe-async/latest/maybe_async/).

*   In some `no_std` environments, floating-point operations are not available.
    I added `num-traits` as a dependency, which reimplements those operations with `libm`.
    This is gated behind a feature `std`.

*   Finally, I set the right features of the dependencies so that they would also be `no_std`.
    Mostly, I disabled default features and enabled `features = ["libm"]`.

The result is a crate that can be used in `no_std` environments, though it still needs an allocator for dynamic memory.
I guess it would require a non-trivial redesign to make it work without dynamic allocation.

Anyway, as long as a microcontroller has enough memory, it should not be an issue to enable `alloc`.

Moreover, I also implemented a simple firmware using embassy on a ESP32-C3.
I implemented `Instant` on a wrapper around `embassy_time::Instant`, and `Sleeper` on a wrapper around `embassy_time::Timer::after()`.
But I am not sure where to put this example.
It needs a custom cargo configuration, so it cannot be easily placed in the directory `example`.

Note: I do not actually have a LED strip to test it :D
For now this firmware just prints the LEDs values to the serial interface.

2024-11-13 00:56 UTC, DavJCosby commented
> Moreover, I also implemented a simple firmware using embassy on a ESP32-C3.
> I implemented Instant on a wrapper around embassy_time::Instant, and Sleeper on a wrapper around embassy_time::Timer::after().
> But I am not sure where to put this example.
> It needs a custom cargo configuration, so it cannot be easily placed in the directory example.

I've decided to make a separate spatial_led_examples repository. It doesn't make a whole lot of sense to have ratatui as a dev dependency for this crate, and it'd be nice to have some examples for more specific setups like raspberry pi or no_std. I'll hit you up when I've got that all set up and you can dump your example in there.

2024-11-13 01:13 UTC, DavJCosby commented
I noticed a considerable performance impact from switching the std feature flag on glam to libm, likely due to glam's use of std::simd if not for other drawbacks of libm.

This PR compared to Master:
<img width="688" alt="Screenshot 2024-11-12 at 6 01 26 PM" src="https://github.com/user-attachments/assets/4de129c2-6a77-404e-9ca1-a145622df810">

Re-enabling std flag on glam:
<img width="662" alt="Screenshot 2024-11-12 at 6 04 35 PM" src="https://github.com/user-attachments/assets/ed2ce628-b027-46ae-bbfa-4581164c679d">


I think it makes most sense to let glam use std when its available and default to libm when its not. We could also expose access to [core-simd](https://github.com/bitshifter/glam-rs/tree/main#SIMD) for those willing to build on nightly.

2024-11-13 05:19 UTC, DavJCosby requested changes
This is probably the way to go, though I'm open to other suggestions. If you're opting out of std, you should also opt in to libm if you'll need it.

2024-11-13 05:19 UTC, DavJCosby commented on Cargo.toml
> +std = ["glam/std"]
```suggestion
std = ["glam/std", "palette/std"]
libm = ["glam/libm", "palette/libm"]
```

2024-11-13 05:19 UTC, DavJCosby commented on Cargo.toml
>  ] }
```suggestion
glam = { version = "0.29", default-features = false, features = [] }
palette = { version = "0.7", default-features = false, features = ["approx"] }
```

2024-11-13 05:35 UTC, DavJCosby requested changes

2024-11-14 15:53 UTC, claudiomattera commented on src/driver/mod.rs
Yeah, this makes sense.
I was thinking to do the same, but I could not find a good name.
`CustomDriver` and `CustomScheduler` sound perfect.

2024-11-14 22:29 UTC, DavJCosby approved these changes
Looks great, thanks again!

2024-11-14 22:31 UTC, merged